print('file: PointEstVarNormal.R')
# Estimate variance (sigma^2) from random sample of normal distribution
set.seed(1953)
M = 1000   # number of Monte-Carlo runs
n = 5      # sample size
varest = numeric(M)
for(m in 1:M) varest[m]=var(rnorm(n))
# png('MCvarNormal160227.png',width=16,height=16,units='cm',res=300)
hist(varest,30,col='blue',xlab=NA,main='',las=1,cex.lab=1.5)
title(xlab=TeX('$\\hat{\\sigma^2}_a = \\frac{1}{n-1} \\sum_j (x_j - \\hat{\\mu})^2$'),line=4.3,cex.lab=1.5)
meanvarest = mean(varest); print(c(round(meanvarest,3),'meanvarest'))  # 1.041  (expected: close to sigma^2 = 1)
varvarest = var(varest); print(c(round(varvarest,3),'varvarest'))    # 0.558  (no expectation)
sdvarest = sd(varest); print(c(round(sdvarest,3),'sdvarest'))      # 0.747  (no expectation)
meanvarestr = round(meanvarest,3); varvarestr = round(varvarest,3); sdvarestr = round(sdvarest,3)
text(3.5,130,bquote(~mean(hat(sigma^2)[a]) == .(meanvarestr)),col='blue',cex=1.5)
text(3.5,115,bquote(~var(hat(sigma^2)[a]) == .(varvarestr)),col='blue',cex=1.5)
text(3.5,100,bquote(~sd(hat(sigma^2)[a]) == .(sdvarestr)),col='blue',cex=1.5)
abline(v=1,col='black',lty=1)
abline(v=meanvarest,col='blue',lty=4)
# dev.off()