print('file: SolutionPointEstCorGuessPDFs.R')
# EXERCISE & SOLUTION: properties of samples generated by sampleUcorFct()
set.seed(1953)
source('sampleUcorFct.R')
r = 0.7 # desired (specified) correlation
n = 2e3
q=sampleUcorFct(r,n); x=q[1:n]; y=q[(n+1):(2*n)]; covEst = cov(x,y)
print(c(round(covEst,4),'covEst'))
print(c(round(sd(x),4),'sd(x)'))
print(c(round(sd(y),4),'sd(y)'))
xmean = mean(x); ymean = mean(y)
sflag = 1
if (sflag == 2) {
  # png('HistyExer200708.png',width=16,height=16,units='cm',res=300)
  hist(y,breaks=20,col='blue',main='',las=1,cex.lab=1.5)
  # dev.off()
}
if (sflag == 1) {
  # png('HistxExer200708.png',width=16,height=16,units='cm',res=300)
  hist(x,breaks=20,col='blue',main='',las=1,cex.lab=1.5)
  # dev.off()
}